# Generated by Django 5.1.1 on 2024-10-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cosmetics',
            new_name='shoes',
        ),
    ]
