# Generated by Django 5.1.1 on 2024-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='device',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
