# Generated by Django 5.1.2 on 2025-07-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electronics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electronics",
            options={"ordering": ["-release_date"]},
        ),
    ]
