# Generated by Django 5.1.1 on 2024-10-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clothes',
            new_name='fashion',
        ),
    ]
