# Generated by Django 5.1.1 on 2024-10-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watches',
            old_name='images',
            new_name='image',
        ),
    ]
