# Generated by Django 5.1.1 on 2024-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_rename_images_watches_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='name',
            field=models.CharField(default='watch', max_length=100),
            preserve_default=False,
        ),
    ]
