# Generated by Django 5.1.2 on 2025-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watches", "0002_rename_images_watches_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="watches",
            name="name",
            field=models.CharField(default="watches", max_length=100),
            preserve_default=False,
        ),
    ]
